export interface SEOMeta {
  title: string;
  description: string;
  keywords: string[];
  h1: string;
}

export const seoMeta: Record<string, SEOMeta> = {
  '/': {
    title: 'Klempner München 24h Notdienst | Sanitär ab 81€ | AquaPro 24',
    description: 'Klempner München ✓ 24/7 Notdienst ✓ Sanitärinstallateur ✓ Festpreis ab 81€ ✓ 30 Min Anfahrt ✓ Rohrbruch & Heizung. Tel: 089 444438872',
    h1: 'Klempner München – Sanitär & Heizung Notdienst 24/7',
    keywords: [
      'Klempner München', 'Sanitär München', 'Sanitärinstallateur München', 'Sanitärinstallateure München',
      'Installateur München', 'Klempner Notdienst München', 'Sanitär Notdienst München',
      'Klempner München 24 Stunden', 'Notfall Klempner München', 'Klempner München sofort',
      'Klempner in meiner Nähe München', 'Klempner München Wochenende', 'Klempner München Feiertag',
      'Gas Wasserinstallateur München', 'Anlagenmechaniker SHK München', 'SHK München',
      'Sanitär Heizung Klima München', 'Heizungsbauer München', 'Heizungsinstallateur München',
      'Klempner München Kosten', 'Klempner München Preise', 'günstiger Klempner München',
      'Klempner München Festpreis', 'Klempner München Kostenvoranschlag',
      'bester Klempner München', 'Klempner München Empfehlung', 'Klempner München Bewertungen',
      'Klempner München geprüft', 'Klempner München seriös', 'Klempner München ohne Abzocke',
      'Sanitär Notdienst München 24h', 'Sanitär Notdienst München günstig',
      'Klempner München Rohrbruch', 'Klempner München Heizung defekt',
      'Wasserschaden München Klempner', 'Installateur Notdienst München',
      'Heizung München', 'Heizungsreparatur München', 'Rohrreinigung München',
      'Rohrbruch München', 'Abfluss verstopft München', 'WC verstopft München',
      'Wasserhahn wechseln München', 'Badsanierung München', 'Wärmepumpe München 2026',
    ],
  },
  '/sanitaer': {
    title: 'Sanitär München | Rohrbruch & Armaturen ab 81€ | AquaPro 24',
    description: 'Sanitär München ✓ Sanitärinstallateur ✓ Rohrbruch Soforthilfe ✓ Armaturen Austausch ✓ WC Reparatur ✓ Festpreis ab 81€. Tel: 089 444438872',
    h1: 'Sanitär München – Sanitärinstallateur für Rohrbruch, Armaturen & WC',
    keywords: [
      'Sanitär München', 'Sanitärinstallateur München', 'Sanitärinstallateure München',
      'Sanitärinstallation München', 'Sanitärtechnik München', 'Sanitärfirma München',
      'Sanitär Service München', 'Sanitär Reparatur München', 'Sanitärbetrieb München',
      'Klempner München', 'Klempner Sanitär München', 'Installateur Sanitär München',
      'Rohrreinigung München', 'Rohrbruch München', 'Rohrbruch reparieren München',
      'Rohrbruch Soforthilfe München', 'Wasserrohr geplatzt München',
      'Abfluss verstopft München', 'Abfluss reinigen München', 'Abflussreinigung München',
      'WC verstopft München', 'WC Reparatur München', 'Toilette verstopft München',
      'Toilette reparieren München', 'WC Spülkasten reparieren München',
      'Armaturen München', 'Armaturen austauschen München', 'Armaturen Montage München',
      'Armaturen wechseln München', 'Wasserhahn wechseln München', 'Wasserhahn reparieren München',
      'Wasserhahn tropft München', 'Wasserhahn austauschen München', 'Mischbatterie wechseln München',
      'Kleinteile Dienst München', 'Kleinreparatur Sanitär München', 'Dichtung wechseln München',
      'Siphon wechseln München', 'Eckventil tauschen München', 'Perlatoren wechseln München',
      'Waschbecken montieren München', 'Waschbecken anschließen München',
      'Spüle einbauen München', 'Küchenarmatur wechseln München',
      'Dusche reparieren München', 'Duscharmatur wechseln München', 'Brauseschlauch wechseln München',
      'Wasseranschluss München', 'Wasserleitung reparieren München',
      'Grohe Montage München', 'Hansgrohe Installateur München', 'Geberit Montage München',
      'HANSA Armaturen München', 'Ideal Standard München',
      'Sanitär Notdienst München', 'Sanitär Notdienst 24h München', 'Sanitär Notruf München',
      'Wasserschaden München', 'Wasserschaden Soforthilfe München',
      'Sanitär Festpreis München', 'Sanitär Kosten München', 'Sanitär günstig München',
    ],
  },
  '/heizung': {
    title: 'Heizung München | Reparatur & Wartung ab 154€ | AquaPro 24',
    description: 'Heizung München ✓ Heizungsreparatur ✓ Wartung ✓ Austausch ✓ Gasheizung ✓ Ölheizung ✓ Festpreis ab 154€ ✓ Viessmann, Vaillant, Buderus. Tel: 089 444438872',
    h1: 'Heizung München – Reparatur, Wartung & Modernisierung 2026',
    keywords: [
      'Heizung München', 'Heizungsreparatur München', 'Heizungswartung München',
      'Heizungsinstallateur München', 'Heizungsbauer München', 'Heizungsmonteur München',
      'Heizungsfirma München', 'Heizungstechnik München', 'Heizungsservice München',
      'Heizung reparieren München', 'Heizung defekt München', 'Heizung kaputt München',
      'Heizung ausgefallen München', 'Heizung funktioniert nicht München',
      'Heizung wird nicht warm München', 'Heizung macht Geräusche München',
      'Heizung verliert Wasser München', 'Heizung entlüften München',
      'Heizungswasser nachfüllen München', 'Heizkörper tauschen München',
      'Thermostat wechseln München', 'Thermostatventil tauschen München',
      'Heizungsaustausch München', 'Heizung erneuern München', 'Heizungsmodernisierung München',
      'Heizungstausch München 2026', 'alte Heizung austauschen München',
      'Gasheizung München', 'Gasheizung reparieren München', 'Gasheizung Wartung München',
      'Gastherme München', 'Gastherme reparieren München', 'Gastherme warten München',
      'Ölheizung München', 'Ölheizung reparieren München', 'Ölbrenner Wartung München',
      'Brennwerttherme München', 'Brennwertkessel München',
      'Viessmann Heizung München', 'Vaillant Heizung München', 'Buderus Heizung München',
      'Wolf Heizung München', 'Junkers Heizung München', 'Brötje Heizung München',
      'Heizung Notdienst München', 'Heizung Notdienst 24h München',
      'Heizungsausfall München', 'Heizungsausfall Notdienst München',
      'Heizung Kosten München', 'Heizung Festpreis München',
      'Zentralheizung München', 'Etagenheizung München', 'Heizungsanlage München',
      'GEG 2026 München', 'Heizungsgesetz München', 'Heizungspflicht 2026 München',
    ],
  },
  '/bad': {
    title: 'Badsanierung München | Badumbau ab 16.000€ | AquaPro 24',
    description: 'Badsanierung München ✓ Komplettumbau ✓ barrierefreies Bad ✓ KfW-Förderung ✓ Festpreis ab 16.000€ ✓ Planung & Ausführung aus einer Hand. Tel: 089 444438872',
    h1: 'Badsanierung München – Komplettumbau vom Profi 2026',
    keywords: [
      'Badsanierung München', 'Badumbau München', 'Badezimmer sanieren München',
      'Bad renovieren München', 'Badmodernisierung München', 'Komplettbad München',
      'barrierefreies Bad München', 'behindertengerechtes Bad München', 'altersgerechtes Bad München',
      'Bad seniorengerecht München', 'bodengleiche Dusche München', 'ebenerdige Dusche München',
      'Dusche statt Badewanne München', 'Badewanne zu Dusche umbauen München',
      'Badewanne einbauen München', 'Badewanne austauschen München',
      'Fliesenleger Bad München', 'Fliesen Bad München', 'Badezimmer Fliesen München',
      'Bad planen München', 'Badezimmer planen München', 'Badplanung München',
      'kleines Bad sanieren München', 'Gäste-WC sanieren München',
      'Bad komplett München', 'Bad Komplettangebot München', 'Bad Festpreis München',
      'Bad Kosten München', 'Badsanierung Kosten München', 'Was kostet Badsanierung München',
      'KfW Bad Förderung München', 'KfW 455-B München', 'Zuschuss Badsanierung München',
      'Sanitärobjekte München', 'Waschtisch montieren München',
      'Badezimmer Design München', 'modernes Bad München',
    ],
  },
  '/waermepumpe': {
    title: 'Wärmepumpe München | Einbau & BAFA 70% | AquaPro 24',
    description: 'Wärmepumpe München ✓ Einbau vom Profi ✓ BAFA-Förderung bis 70% ✓ KfW 458 Kredit ✓ Luft-Wasser-Wärmepumpe ✓ Kostenlose Beratung 2026. Tel: 089 444438872',
    h1: 'Wärmepumpe München – Einbau & Förderung bis 70% 2026',
    keywords: [
      'Wärmepumpe München', 'Wärmepumpe installieren München', 'Wärmepumpe einbauen München',
      'Wärmepumpe Kosten München', 'Wärmepumpe Preis München', 'Was kostet Wärmepumpe München',
      'Luft-Wasser-Wärmepumpe München', 'Luft-Luft-Wärmepumpe München',
      'Erdwärmepumpe München', 'Sole-Wasser-Wärmepumpe München',
      'Wärmepumpe nachrüsten München', 'Wärmepumpe Altbau München',
      'Wärmepumpe Neubau München', 'Wärmepumpe Bestandsgebäude München',
      'BAFA Förderung Wärmepumpe München 2026', 'BAFA Zuschuss Wärmepumpe München',
      'KfW 458 München', 'KfW Kredit Wärmepumpe München',
      'Wärmepumpe Förderung München 2026', 'Heizungstausch Förderung München',
      'Gasheizung auf Wärmepumpe umrüsten München', 'Ölheizung auf Wärmepumpe München',
      'Heizungstausch München 2026', 'Heizung erneuern Förderung München',
      'Viessmann Wärmepumpe München', 'Vaillant Wärmepumpe München',
      'Bosch Wärmepumpe München', 'Daikin Wärmepumpe München',
      'Wärmepumpe Wartung München', 'Wärmepumpe Service München',
      'Wärmepumpe Beratung München', 'Energieberater Wärmepumpe München',
      'GEG Wärmepumpe München 2026', 'Heizungspflicht Wärmepumpe 2026',
      'Klimabonus München', 'Geschwindigkeitsbonus Wärmepumpe',
    ],
  },
  '/notdienst-muenchen': {
    title: 'Notdienst München 24/7 | Klempner Sanitär Soforthilfe | AquaPro 24',
    description: 'Notdienst München 24/7 ✓ Rohrbruch ✓ Wasserschaden ✓ Heizungsausfall ✓ 30 Min Anfahrt ✓ Festpreis ✓ Kein Aufschlag nachts & Wochenende. Sofort: 089 444438872',
    h1: 'Notdienst München 24/7 – Rohrbruch & Heizungsausfall Soforthilfe',
    keywords: [
      'Notdienst München', 'Notdienst München 24h', 'Klempner Notdienst München',
      'Sanitär Notdienst München', 'Heizung Notdienst München',
      'Notdienst München sofort', 'Notdienst München schnell', 'Notdienst München Nacht',
      'Notdienst München Wochenende', 'Notdienst München Sonntag', 'Notdienst München Feiertag',
      'Rohrbruch Notdienst München', 'Wasserschaden Notdienst München',
      'Heizungsausfall Notdienst München', 'Heizung ausgefallen München',
      'WC verstopft Notdienst München', 'Abfluss verstopft Notdienst München',
      'Wasserrohr geplatzt München', 'Wasserrohrbruch München',
      'Notdienst München Festpreis', 'Notdienst München Kosten', 'Notdienst München günstig',
      'Notdienst München seriös', 'Notdienst München ohne Abzocke',
      'Notfall Klempner München', 'Notfall Installateur München', 'Notfall Sanitär München',
      'Klempner Soforthilfe München', 'Sanitär Soforthilfe München',
      'Notdienst München Preise', 'Was kostet Notdienst München',
      'Rohrreinigung Notdienst München', 'Kanalreinigung Notdienst München',
    ],
  },
  '/termin': {
    title: 'Termin München online buchen | Klempner Sanitär | AquaPro 24',
    description: 'Handwerker Termin München ✓ Online buchen ✓ Klempner ✓ Sanitärinstallateur ✓ Heizungsmonteur ✓ Wunschtermin wählen ✓ Bestätigung sofort. Tel: 089 444438872',
    h1: 'Termin München – Klempner & Sanitär online buchen',
    keywords: [
      'Termin buchen München', 'Handwerker Termin München', 'Online Terminbuchung München',
      'Klempner Termin München', 'Sanitär Termin München', 'Installateur Termin München',
      'Heizungsmonteur Termin München', 'Handwerker online buchen München',
      'Sanitärinstallateur Termin München', 'Klempner Terminvereinbarung München',
      'Handwerker Termin online München', 'Sanitär Termin online München',
    ],
  },
  '/kontakt': {
    title: 'Kontakt AquaPro 24 München | Angebot anfordern | AquaPro 24',
    description: 'Kontakt AquaPro 24 München ✓ Klempner Anfrage ✓ Sanitär Angebot ✓ Kostenlose Beratung ✓ Schnelle Antwort ✓ Tel: 089 444438872 ✓ info@aquapro24.de',
    h1: 'Kontakt AquaPro 24 München – Sanitär & Heizung',
    keywords: [
      'Kontakt AquaPro 24 München', 'Klempner Kontakt München', 'Sanitär Kontakt München',
      'Klempner Angebot München', 'Sanitär Angebot München', 'Heizung Angebot München',
      'Kostenvoranschlag Klempner München', 'Kostenvoranschlag Sanitär München',
      'Beratung Sanitär München', 'Beratung Heizung München', 'AquaPro 24 Telefon',
    ],
  },
  '/faq': {
    title: 'FAQ Klempner München | Sanitär & Heizung Preise | AquaPro 24',
    description: 'FAQ Klempner München ✓ Was kostet Sanitär? ✓ Notdienst Preise ✓ Heizung Kosten ✓ Rohrreinigung Preise ✓ Alle Antworten verständlich erklärt.',
    h1: 'FAQ – Häufige Fragen zu Klempner, Sanitär & Heizung München 2026',
    keywords: [
      'FAQ Klempner München', 'Klempner Kosten München', 'Sanitär Kosten München',
      'Was kostet Klempner München', 'Was kostet Sanitär München', 'Klempner Preise München',
      'Sanitär Preise München', 'Heizung Kosten München', 'Heizungsreparatur Kosten München',
      'Rohrreinigung Kosten München', 'Notdienst Kosten München',
      'Was kostet Rohrreinigung München', 'Was kostet Notdienst München',
      'Badsanierung Kosten München', 'Wärmepumpe Kosten München',
      'Klempner Stundenlohn München', 'Sanitär Stundensatz München',
      'Klempner Anfahrt Kosten München', 'Sanitär Preisliste München 2026',
    ],
  },
  '/ueber-uns': {
    title: 'AquaPro 24 München | Sanitär & Heizung seit 2005',
    description: 'AquaPro 24 München ✓ Partnernetzwerk seit 2005 ✓ Geprüfte Fachbetriebe ✓ Sanitärinstallateure ✓ Heizungsbauer ✓ Festpreisgarantie ✓ 2.800+ zufriedene Kunden.',
    h1: 'AquaPro 24 – Ihr Sanitär & Heizung Partnernetzwerk seit 2005',
    keywords: [
      'AquaPro 24 München', 'Sanitär Partnernetzwerk München', 'Heizung Partnernetzwerk München',
      'Klempner Netzwerk München', 'geprüfte Sanitärinstallateure München',
      'Sanitär Fachbetrieb München', 'Heizung Fachbetrieb München', 'Meisterbetrieb München',
      'seit 2005 München', 'Sanitär Erfahrung München', 'Heizung Erfahrung München',
    ],
  },
  '/impressum': {
    title: 'Impressum AquaPro 24 München | Mustafa Sakar',
    description: 'Impressum AquaPro 24: Mustafa Sakar, Hardenbergstr. 4, 80992 München. Ihr Sanitär & Heizung Partnernetzwerk seit 2005.',
    h1: 'Impressum AquaPro 24',
    keywords: ['Impressum AquaPro 24', 'Mustafa Sakar', 'München 80992', 'Hardenbergstr 4'],
  },
  '/datenschutz': {
    title: 'Datenschutz DSGVO AquaPro 24 München – Ihre Rechte',
    description: 'Datenschutzerklärung AquaPro 24 München: DSGVO-konform, transparente Datenverarbeitung, Ihre Rechte als Nutzer.',
    h1: 'Datenschutzerklärung AquaPro 24',
    keywords: ['Datenschutz', 'DSGVO', 'AquaPro 24', 'Datenschutzerklärung'],
  },
  '/agb': {
    title: 'AGB AquaPro 24 Sanitär München – Festpreis & Garantie',
    description: 'AGB AquaPro 24 München: Allgemeine Geschäftsbedingungen für Sanitär & Heizung. Festpreisgarantie, Gewährleistung, faire Konditionen.',
    h1: 'Allgemeine Geschäftsbedingungen AquaPro 24',
    keywords: ['AGB', 'Geschäftsbedingungen', 'AquaPro 24', 'Festpreis'],
  },
  '/foerderung': {
    title: 'Förderung Heizung München | BAFA KfW bis 70% | AquaPro 24',
    description: 'Förderung Heizung München 2026 ✓ BAFA bis 70% ✓ KfW 458 Kredit ✓ Steuerbonus ✓ Wärmepumpe ✓ Heizungstausch ✓ Kostenlose Förderberatung. Tel: 089 444438872',
    h1: 'Förderung Heizung München 2026 – BAFA bis 70% + KfW 458',
    keywords: [
      'Förderung Heizung München 2026', 'BAFA Förderung 2026', 'KfW 458 München',
      'Wärmepumpe Förderung München 2026', 'Heizungsförderung München 2026',
      'BAFA Zuschuss Heizung', 'Steuerbonus Heizung München', 'Klimabonus 2026',
      'Heizungstausch Förderung 2026', 'Förderung Gasheizung München',
      'Förderung Ölheizung München', 'Förderung erneuerbare Energien München',
      'GEG 2026 Förderung', 'Energieberater München Förderung',
      'Geschwindigkeitsbonus BAFA 2026', 'Einkommensbonus BAFA München',
      'iSFP Bonus München', 'individueller Sanierungsfahrplan München',
    ],
  },
  '/haustechnik': {
    title: 'Haustechnik München | Gas Wasser Lüftung | AquaPro 24',
    description: 'Haustechnik München ✓ Gasinstallation ✓ Wasserinstallation ✓ Lüftung ✓ Smart Home ✓ Sanitärtechnik komplett ✓ Festpreise. Tel: 089 444438872',
    h1: 'Haustechnik München – Gas, Wasser, Lüftung komplett 2026',
    keywords: [
      'Haustechnik München', 'Gasinstallation München', 'Wasserinstallation München',
      'Lüftungsanlage München', 'KWL München', 'kontrollierte Wohnraumlüftung München',
      'Smart Home Haustechnik München', 'Gebäudetechnik München',
      'Gas Wasser Installateur München', 'Gastherme Installation München',
      'Gasleitung München', 'Gasanschluss München', 'Gaszähler München',
      'Wasseranschluss München', 'Wasserleitung München', 'Wasserfilter München',
      'Lüftung Bad München', 'Lüftung Küche München', 'Dunstabzug München',
      'Haustechnik Neubau München', 'Haustechnik Altbau München',
      'SHK Betrieb München', 'SHK Handwerker München',
    ],
  },
  '/armaturen': {
    title: 'Armaturen München | Wasserhahn wechseln ab 89€ | AquaPro 24',
    description: 'Armaturen München ✓ Wasserhahn wechseln ab 89€ ✓ Grohe ✓ Hansgrohe ✓ HANSA ✓ Mischbatterie ✓ Küchenarmatur ✓ Festpreis. Tel: 089 444438872',
    h1: 'Armaturen München – Wasserhahn wechseln & Montage 2026',
    keywords: [
      'Armaturen München', 'Armaturen austauschen München', 'Armaturen Montage München',
      'Armaturen wechseln München', 'Armatur reparieren München', 'Armatur tropft München',
      'Wasserhahn wechseln München', 'Wasserhahn reparieren München', 'Wasserhahn montieren München',
      'Wasserhahn tropft München', 'Wasserhahn austauschen München',
      'Wasserhahn Küche wechseln München', 'Küchenarmatur München', 'Küchenarmatur wechseln München',
      'Mischbatterie wechseln München', 'Mischbatterie reparieren München',
      'Badarmatur München', 'Badarmatur wechseln München',
      'Duscharmatur wechseln München', 'Duscharmatur reparieren München',
      'Thermostatarmatur München', 'Thermostatarmatur wechseln München',
      'Grohe Armatur München', 'Hansgrohe Armatur München', 'HANSA Armatur München',
      'Ideal Standard Armatur München', 'Blanco Armatur München',
      'Einhebelmischer wechseln München', 'Zweigriffarmatur München',
      'Niederdruck-Armatur München', 'Hochdruck-Armatur München',
      'Armatur Kosten München', 'Wasserhahn wechseln Kosten München',
      'Armaturen Kleinteile Service München',
    ],
  },
  '/rohrreinigung': {
    title: 'Rohrreinigung München 24/7 | ab 81€ Festpreis | AquaPro 24',
    description: 'Rohrreinigung München ✓ Abfluss verstopft ✓ WC verstopft ✓ Notdienst 24/7 ✓ Festpreis ab 81€ ✓ 30 Min Anfahrt ✓ Kanalreinigung. Tel: 089 444438872',
    h1: 'Rohrreinigung München – Abfluss verstopft? Soforthilfe 24/7',
    keywords: [
      'Rohrreinigung München', 'Rohrreinigung München Notdienst', 'Rohrreinigung München 24h',
      'Rohrreinigung München Kosten', 'Rohrreinigung München Preise', 'Rohrreinigung München Festpreis',
      'Abfluss verstopft München', 'Abfluss reinigen München', 'Abflussreinigung München',
      'Abfluss verstopft Küche München', 'Abfluss verstopft Bad München',
      'WC verstopft München', 'Toilette verstopft München', 'Klo verstopft München',
      'WC verstopft Notdienst München', 'Toilette verstopft Soforthilfe München',
      'Kanalreinigung München', 'Kanalreinigung München Kosten',
      'Rohr verstopft München', 'Rohr reinigen München', 'Rohrleitung verstopft München',
      'Abwasserrohr verstopft München', 'Fallrohr verstopft München',
      'Dusche verstopft München', 'Waschbecken verstopft München', 'Spüle verstopft München',
      'Rohrreinigung Spirale München', 'Hochdruck Rohrreinigung München',
      'TV Kanalinspektion München', 'Kamerabefahrung Kanal München',
      'Rohrreinigung günstig München', 'Rohrreinigung seriös München',
      'Was kostet Rohrreinigung München', 'Rohrreinigung Preisliste München',
    ],
  },
  '/warmwasser': {
    title: 'Durchlauferhitzer München | Boiler & Warmwasser | AquaPro 24',
    description: 'Durchlauferhitzer München ✓ Boiler Reparatur ✓ Warmwasserspeicher ✓ kein Warmwasser Soforthilfe ✓ Installation ab 120€ ✓ Festpreis. Tel: 089 444438872',
    h1: 'Warmwasser München – Durchlauferhitzer, Boiler & Speicher 2026',
    keywords: [
      'Durchlauferhitzer München', 'Durchlauferhitzer reparieren München',
      'Durchlauferhitzer installieren München', 'Durchlauferhitzer einbauen München',
      'Durchlauferhitzer austauschen München', 'Durchlauferhitzer defekt München',
      'Boiler München', 'Boiler reparieren München', 'Boiler austauschen München',
      'Warmwasserspeicher München', 'Warmwasserspeicher reparieren München',
      'Warmwasser München', 'kein Warmwasser München', 'Warmwasser defekt München',
      'Warmwasseraufbereitung München', 'Warmwasserbereiter München',
      'Untertischgerät München', 'Obertischspeicher München',
      'Stiebel Eltron München', 'Vaillant Durchlauferhitzer München',
      'AEG Durchlauferhitzer München', 'Clage Durchlauferhitzer München',
      'elektrischer Durchlauferhitzer München', 'Gas-Durchlauferhitzer München',
      'Durchlauferhitzer Kosten München', 'Was kostet Durchlauferhitzer München',
      'Warmwasser Kosten München', 'Boiler Kosten München',
    ],
  },
  '/badsanierung': {
    title: 'Badsanierung Komplett München | ab 16.000€ | AquaPro 24',
    description: 'Badsanierung München ✓ Komplettumbau ✓ barrierefreies Bad ✓ KfW-Förderung ✓ Festpreis ab 16.000€ ✓ Beratung vor Ort ✓ Alle Gewerke. Tel: 089 444438872',
    h1: 'Badsanierung München – Komplettumbau aus einer Hand 2026',
    keywords: [
      'Badsanierung München', 'Badsanierung München Kosten', 'Badsanierung München Festpreis',
      'Badsanierung komplett München', 'Badumbau München', 'Bad renovieren München',
      'Badezimmer sanieren München', 'Komplettbad München', 'Badezimmer renovieren München',
      'barrierefreies Bad München', 'behindertengerechtes Bad München',
      'altersgerechtes Bad München', 'seniorengerechtes Bad München',
      'bodengleiche Dusche einbauen München', 'ebenerdige Dusche München',
      'Dusche statt Badewanne München', 'Badewanne zu Dusche München',
      'Badewanne einbauen München', 'Whirlpool Bad München',
      'kleines Bad sanieren München', 'Gäste-WC sanieren München', 'Gäste-WC renovieren München',
      'Bad Fliesen München', 'Badezimmer Fliesen legen München',
      'KfW Förderung Bad München', 'Zuschuss barrierefreies Bad München',
      'Was kostet Badsanierung München', 'Badsanierung Kosten pro qm München',
      'Bad sanieren lassen München', 'Badezimmer gestalten München',
    ],
  },
  '/sanitaer-notdienst-24': {
    title: 'Sanitär Notdienst München 24/7 | Soforthilfe | AquaPro 24',
    description: 'Sanitär Notdienst München 24/7 ✓ Rohrbruch ✓ Wasserschaden ✓ WC verstopft ✓ Festpreis ✓ 30 Min Anfahrt ✓ seriös & ohne Abzocke. Jetzt: 089 444438872',
    h1: 'Sanitär Notdienst München 24/7 – Soforthilfe bei Rohrbruch',
    keywords: [
      'Sanitär Notdienst München', 'Sanitär Notdienst München 24h', 'Sanitär Notdienst München günstig',
      'Sanitär Notdienst München Kosten', 'Sanitär Notdienst München Preise',
      'Sanitär Notdienst München Sonntag', 'Sanitär Notdienst München Feiertag',
      'Sanitär Notdienst München Nacht', 'Sanitär Notdienst München Wochenende',
      'Sanitär Notdienst München seriös', 'Sanitär Notdienst München Festpreis',
      'Sanitär Notdienst München ohne Abzocke', 'Sanitär Notdienst München Empfehlung',
      'Sanitär Notdienst München Bewertung', 'Sanitär Notdienst München Meisterbetrieb',
      'Klempner Notdienst München 24h', 'Installateur Notdienst München',
      'Rohrbruch München', 'Rohrbruch Notdienst München', 'Rohrbruch reparieren München',
      'Wasserrohr geplatzt München', 'Wasserrohrbruch München',
      'Wasserschaden München', 'Wasserschaden Soforthilfe München', 'Wasserschaden Notdienst München',
      'WC verstopft Notdienst München', 'Abfluss verstopft Notdienst München',
      'Toilette verstopft Notdienst München', 'Sanitär Notruf München',
      'Sanitär Notdienst München sofort', 'Sanitär Notdienst München schnell',
    ],
  },
  '/heizung-notdienst-24': {
    title: 'Heizung Notdienst München 24/7 | Soforthilfe | AquaPro 24',
    description: 'Heizung Notdienst München 24/7 ✓ Heizung ausgefallen ✓ Heizung wird nicht warm ✓ Gastherme Störung ✓ Festpreis ✓ 30 Min. Jetzt: 089 444438872',
    h1: 'Heizung Notdienst München 24/7 – Soforthilfe bei Heizungsausfall',
    keywords: [
      'Heizung Notdienst München', 'Heizung Notdienst München 24h',
      'Heizung ausgefallen München', 'Heizungsausfall München', 'Heizungsausfall Notdienst München',
      'Heizung defekt München', 'Heizung kaputt München', 'Heizung funktioniert nicht München',
      'Heizung wird nicht warm München', 'Heizung kalt München', 'keine Heizung München',
      'Heizung Störung München', 'Heizung Störcode München',
      'Gastherme Störung München', 'Gastherme defekt München', 'Gastherme kein Warmwasser München',
      'Heizung Notdienst München Kosten', 'Heizung Notdienst München Preise',
      'Heizung Notdienst München günstig', 'Heizung Notdienst München seriös',
      'Heizung Notdienst München Nacht', 'Heizung Notdienst München Wochenende',
      'Heizung Notdienst München Winter', 'Heizung Notdienst München Festpreis',
      'Heizungsmonteur Notdienst München', 'Heizungstechniker Notdienst München',
      'Brenner Störung München', 'Heizkessel defekt München',
    ],
  },
  '/sanitaer-muenchen': {
    title: 'Sanitärinstallateur München | Festpreis | AquaPro 24',
    description: 'Sanitärinstallateur München ✓ Klempner ✓ Reparatur ✓ Installation ✓ Wartung ✓ Sanitärtechnik ✓ Festpreis ✓ Termin in 24h. Tel: 089 444438872',
    h1: 'Sanitärinstallateur München – Klempner schnell & zuverlässig',
    keywords: [
      'Sanitärinstallateur München', 'Sanitärinstallateure München', 'Sanitär München',
      'Klempner München', 'Installateur München', 'Sanitärfachmann München',
      'Sanitärtechniker München', 'Sanitärfirma München', 'Sanitärbetrieb München',
      'Sanitärinstallation München', 'Sanitärtechnik München', 'Sanitär Service München',
      'Sanitär Reparatur München', 'Sanitär Wartung München', 'Sanitär Montage München',
      'Sanitär Anschluss München', 'Sanitär Installation München',
      'Gas Wasserinstallateur München', 'Gas Wasser Installateur München',
      'Anlagenmechaniker SHK München', 'SHK Fachbetrieb München',
      'Sanitär Handwerker München', 'Sanitär Meisterbetrieb München',
      'Sanitär Fachbetrieb München', 'Sanitär Festpreis München',
    ],
  },
  '/heizung-muenchen': {
    title: 'Heizungsservice München | Reparatur & Wartung | AquaPro 24',
    description: 'Heizungsservice München ✓ Reparatur ✓ Wartung ✓ Modernisierung ✓ alle Marken ✓ Festpreis ab 154€ ✓ Termin in 24h. Tel: 089 444438872',
    h1: 'Heizung München – Reparatur, Wartung & Modernisierung 2026',
    keywords: [
      'Heizung München', 'Heizungsservice München', 'Heizungsreparatur München',
      'Heizungswartung München', 'Heizungsmodernisierung München', 'Heizungstausch München',
      'Heizungsfirma München', 'Heizungsbetrieb München', 'Heizungstechnik München',
      'Heizungsbauer München', 'Heizungsinstallateur München', 'Heizungsmonteur München',
      'Heizung erneuern München', 'Heizung austauschen München',
      'Gasheizung München', 'Gastherme München', 'Brennwerttherme München',
      'Ölheizung München', 'Pelletheizung München', 'Fernwärme München',
      'Viessmann München', 'Vaillant München', 'Buderus München', 'Wolf München',
      'Heizung Festpreis München', 'Heizung Kosten München',
      'GEG München 2026', 'Heizungsgesetz München 2026',
    ],
  },
  '/waermepumpe-muenchen': {
    title: 'Wärmepumpe München installieren | BAFA 70% | AquaPro 24',
    description: 'Wärmepumpe München ✓ Installation vom Profi ✓ BAFA bis 70% ✓ KfW 458 ✓ Luft-Wasser ✓ Erdwärme ✓ Kostenlose Beratung. Tel: 089 444438872',
    h1: 'Wärmepumpe München – Installation & Förderung 2026',
    keywords: [
      'Wärmepumpe München', 'Wärmepumpe installieren München', 'Wärmepumpe einbauen München',
      'Wärmepumpe nachrüsten München', 'Wärmepumpe Altbau München',
      'Luft-Wasser-Wärmepumpe München', 'Erdwärmepumpe München',
      'BAFA Förderung Wärmepumpe München', 'KfW 458 Wärmepumpe München',
      'Wärmepumpe Kosten München', 'Wärmepumpe Preis München',
      'Heizungstausch Wärmepumpe München', 'Gasheizung zu Wärmepumpe München',
    ],
  },
  '/fussbodenheizung-muenchen': {
    title: 'Fußbodenheizung München | Nachrüsten & Einbau | AquaPro 24',
    description: 'Fußbodenheizung München ✓ Nachrüsten ✓ Einbau ✓ Reparatur ✓ Spülung ✓ Festpreis ✓ alle Systeme. Tel: 089 444438872',
    h1: 'Fußbodenheizung München – Nachrüsten & Einbau 2026',
    keywords: [
      'Fußbodenheizung München', 'Fußbodenheizung nachrüsten München',
      'Fußbodenheizung einbauen München', 'Fußbodenheizung verlegen München',
      'Fußbodenheizung reparieren München', 'Fußbodenheizung spülen München',
      'Fußbodenheizung entlüften München', 'Fußbodenheizung Kosten München',
      'Fußbodenheizung wird nicht warm München', 'Fußbodenheizung defekt München',
      'Fußbodenheizung hydraulischer Abgleich München',
    ],
  },
  '/badsanierung-muenchen': {
    title: 'Badumbau München | Badsanierung & KfW-Förderung | AquaPro 24',
    description: 'Badumbau München ✓ Badsanierung ✓ barrierefreies Bad ✓ KfW-Förderung ✓ Komplettpreis ✓ stressfrei ✓ alle Gewerke. Tel: 089 444438872',
    h1: 'Badsanierung München – Komplettumbau stressfrei & modern 2026',
    keywords: [
      'Badsanierung München', 'Badumbau München', 'Bad renovieren München',
      'Badezimmer sanieren München', 'Komplettbad München',
      'barrierefreies Bad München', 'bodengleiche Dusche München',
      'Badezimmer modernisieren München', 'Bad komplett München',
      'Badsanierung Kosten München', 'Bad Festpreis München',
      'KfW Bad München', 'Zuschuss Bad München',
    ],
  },
  '/fussbodenheizung': {
    title: 'Fußbodenheizung München | Installation & Reparatur | AquaPro 24',
    description: 'Fußbodenheizung München ✓ Installation ✓ Reparatur ✓ Spülung ✓ Entlüftung ✓ hydraulischer Abgleich ✓ Festpreis ab 154€. Tel: 089 444438872',
    h1: 'Fußbodenheizung München – Installation & Reparatur 2026',
    keywords: [
      'Fußbodenheizung München', 'Fußbodenheizung Installation München',
      'Fußbodenheizung Reparatur München', 'Fußbodenheizung Spülung München',
      'Fußbodenheizung Entlüftung München', 'Fußbodenheizung Wartung München',
      'Fußbodenheizung hydraulischer Abgleich München',
      'Fußbodenheizung nachrüsten München', 'Fußbodenheizung einbauen München',
      'Fußbodenheizung Kosten München', 'Fußbodenheizung verlegen München',
      'Fußbodenheizung wird nicht warm', 'Fußbodenheizung Thermostat München',
      'Fußbodenheizung Verteiler München', 'Fußbodenheizung Stellmotor München',
    ],
  },
  '/foerderantrag': {
    title: 'Förderantrag München | BAFA KfW kostenlos | AquaPro 24',
    description: 'Förderantrag München ✓ BAFA Antrag ✓ KfW 458 ✓ kostenloser Service ✓ bis 70% Zuschuss ✓ Wärmepumpe ✓ Heizungstausch. Tel: 089 444438872',
    h1: 'Förderantrag München – BAFA & KfW kostenlos 2026',
    keywords: [
      'Förderantrag München', 'BAFA Antrag München', 'KfW Antrag München',
      'Förderung Heizung Antrag München', 'BAFA Antrag stellen München',
      'KfW 458 Antrag München', 'Förderantrag kostenlos München',
      'Förderservice München', 'Förderberatung München',
    ],
  },
  '/foerderantrag-heizung': {
    title: 'Förderantrag Heizung München | BAFA bis 70% | AquaPro 24',
    description: 'Förderantrag Heizung München ✓ Wärmepumpe BAFA ✓ bis 70% Zuschuss ✓ kostenloser Förderservice ✓ Heizungstausch 2026. Tel: 089 444438872',
    h1: 'Förderantrag Heizung München – BAFA Wärmepumpe bis 70% 2026',
    keywords: [
      'Förderantrag Heizung München', 'BAFA Wärmepumpe Antrag', 'Heizungsförderung Antrag',
      'Förderantrag Heizungstausch München', 'BAFA Antrag Heizung München 2026',
      'KfW 458 Heizung München', 'Förderung Heizungstausch München 2026',
    ],
  },
  '/foerderrechner': {
    title: 'Förderrechner München | BAFA KfW berechnen | AquaPro 24',
    description: 'Förderrechner München ✓ BAFA Zuschuss berechnen ✓ KfW 458 ✓ Wärmepumpe ✓ Heizungstausch ✓ Sofort-Ergebnis 2026. Kostenlos berechnen!',
    h1: 'Förderrechner München – BAFA & KfW Förderung berechnen 2026',
    keywords: [
      'Förderrechner München', 'BAFA Rechner München', 'KfW Förderung berechnen München',
      'Wärmepumpe Förderung berechnen', 'Heizungstausch Förderung berechnen',
      'BAFA Zuschuss Rechner 2026', 'Förderung berechnen Heizung München',
    ],
  },
  '/barrierefreiheit': {
    title: 'Barrierefreiheitserklärung – AquaPro 24 München WCAG 2.1 AA',
    description: 'Barrierefreiheitserklärung AquaPro 24: WCAG 2.1 AA / BITV 2.0 konform. Tastaturnavigation, Screenreader, Kontrastmodus.',
    h1: 'Barrierefreiheitserklärung – AquaPro 24 München',
    keywords: ['Barrierefreiheit', 'WCAG 2.1 AA', 'BITV 2.0', 'Barrierefreiheitserklärung'],
  },
  '/cookie-richtlinie': {
    title: 'Cookie-Richtlinie AquaPro 24 München – DSGVO-konform',
    description: 'Cookie-Richtlinie AquaPro 24 München: Transparente Cookie-Nutzung, DSGVO-konform. Ihre Datenschutzrechte.',
    h1: 'Cookie-Richtlinie AquaPro 24',
    keywords: ['Cookie Richtlinie', 'DSGVO', 'Cookie-Einstellungen', 'Datenschutz'],
  },
  '/ratgeber': {
    title: 'Sanitär Ratgeber München | Klempner Tipps Kosten 2026 | AquaPro 24',
    description: 'Sanitär Ratgeber München ✓ Klempner Tipps ✓ Kosten sparen ✓ Heizung Ratgeber ✓ Bad Tipps ✓ Profi-Anleitungen 2026. Jetzt lesen!',
    h1: 'Sanitär & Heizung Ratgeber München 2026',
    keywords: [
      'Sanitär Ratgeber München', 'Klempner Tipps München', 'Heizung Ratgeber München',
      'Bad Ratgeber München', 'Sanitär Tipps', 'Heizung Tipps',
      'Rohrreinigung Tipps', 'Abfluss verstopft Hausmittel', 'Heizung entlüften Anleitung',
      'Wasserhahn tropft was tun', 'Rohrbruch was tun', 'Heizung ausgefallen was tun',
      'Sanitär Kosten sparen', 'Klempner Kosten sparen München',
      'Heizkosten senken München', 'Wasser sparen Tipps München',
    ],
  },
};

export function getSEOMeta(path: string): SEOMeta | undefined {
  return seoMeta[path];
}
